[package]
name = "nerd_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
poise = "0.6.1"
serenity = "0.12"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
